### PR TITLE
Revising README and other repository intro docs

### PR DESCRIPTION
**Pull request by dbrower**
* Remove old content, especially now that we are using Go modules. This
  means a lot of the GOPATH text no longer applies

* Add blackpearl to README

### CODE REVIEW

**Review by msuhovec — COMMENTED** [review]
`These homebrew recipes are already included DLT dotfiles.`

Reading the README after the mods, I encountered this line. It is not part of ypur changes, but I'm wondering if it's still needed?

**Comment by dbrower** [comment]
Hmm. Yeah, maybe it is not needed anymore. Let me go over the file again.

**Comment by dbrower** [comment]
@msuhovec Are the revised installation and running instructions clearer now?

**Review by msuhovec — APPROVED** [review]

**Comment by msuhovec** [comment]
yes.

**Pull request merged**
