### PR TITLE
Add BlackPearl storage driver

### PR DESCRIPTION
**Pull request by dbrower**
It interacts directly with a BlackPearl device via API.

Since the BlackPearl has no way to upload a file without knowing the
size, we use a local temporary file to store uploads before sending the
whole thing to the device.

To be done next is hooking the black pearl into the configuration code
so bendo can use it.

### CODE REVIEW

**Review by msuhovec — COMMENTED** [review]
github.com/SpectraLogic/ds3_go_sdk v5.2.0+incompatible - the name does not give me a warm feeling.

**Comment by dbrower** [comment]
Yeah, that is how they are versioning their SDK.

I based this off of the S3 code, changing it for two reasons. First it uses the BlackPearl API instead of the S3 API. Second, it saves uploads to a temporary file because of the requirement to know the file size for uploads. Wasn't sure how else to handle that. I'll add a configuration so we can configure the directory to use for these (possibly large) temporary files.

**Review by msuhovec — COMMENTED** [review]
What do you expect the name-value pair in the bendo config file to look like? 

ds3://10.255.10.105/<prefix, if any>?

**Review by msuhovec — APPROVED** [review]

**Comment by msuhovec** [comment]
I noticed that they have a separate appliance (Rio?) that looks like an
upload broker tlo the black pearl. Wondering how others deal with this.

**Comment by dbrower** [comment]
I think we have a strange use case. Others probably move files from a filesystem to the BP. We aggregate files and stream the (newly created) zip file. We don't know the precise size beforehand.

**Comment by dbrower** [comment]
> What do you expect the name-value pair in the bendo config file to look like?
> 
> ds3://10.255.10.105/<prefix, if any>?

Yeah, I'm thinking something similar to that. Maybe `bp://` or `blackpearl://`. That is the next thing to add.

**Pull request merged**
