### PR TITLE
adding sha256 checksum to GET header as X-Content-Sha256

### PR DESCRIPTION
**Pull request by msuhovec**
#32

### CODE REVIEW

**Comment by dbrower** [comment]
This looks good! Only comment is to also set the `Content-Length` header on `HEAD` requests. It is a common pattern to use a HEAD request to see how big the content body would be when doing a GET.

**Comment by msuhovec** [comment]
OK

**Comment by dbrower** [comment]
Want to try adding a test for the head request? just see if it sets the cached header, and that it doesn't cache the content.

**Comment by dbrower** [comment]
I fixed the errors in the test I noticed. The main one was a race condition since it takes time for a blob to be asynchronously copied into the cache.

**Pull request merged**
